name: madmom
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python==3.12
  - ffmpeg
  - pip
  - pip:
      - setuptools
      - pretty_midi
      - git+https://github.com/CPJKU/madmom
      - tensorflow==2.19.0
